import os
import sqlite3
from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
from run_plagiarism_system import run_system # 🟢 MEMBER 1's AI

app = Flask(__name__, static_folder='frontend')
CORS(app)

UPLOAD_FOLDER = 'uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

# --- 1. HOST THE WEBSITE (Frontend) ---
@app.route('/')
def home():
    return send_from_directory(app.static_folder, 'index.html')

@app.route('/<path:path>')
def serve_static(path):
    return send_from_directory(app.static_folder, path)

# --- 2. THE REAL ANALYZE ROUTE (Backend) ---
@app.route('/analyze', methods=['POST'])
def analyze():
    if 'file' not in request.files:
        return jsonify({"error": "No file uploaded"}), 400
        
    file = request.files['file']
    if file.filename == '':
        return jsonify({"error": "No file selected"}), 400

    # 1. Save the uploaded file temporarily
    filepath = os.path.join(UPLOAD_FOLDER, file.filename)
    file.save(filepath)

    try:
        # 2. Pass the file directly to Member 1's AI Engine!
        ai_result = run_system(filepath)
        
        # Extract the specific data from the AI result
        score = ai_result.get("score", 0)
        status = ai_result.get("status", "Analysis Complete")
        matched_file = ai_result.get('matched_file', 'None')

        # 3. Save this result into our SQLite Database (NEW!)
        try:
            conn = sqlite3.connect('database.db')
            cursor = conn.cursor()
            cursor.execute('''
                INSERT INTO reports (filename, score, matched_file, status)
                VALUES (?, ?, ?, ?)
            ''', (file.filename, score, matched_file, status))
            conn.commit()
            conn.close()
        except Exception as db_err:
            print("⚠️ Could not save to database:", db_err)
        
        # 4. Send the AI's exact math back to Member 3's UI
        return jsonify({
            "score": score,
            "status": status,
            "details": f"Matched with: {matched_file}"
        })
    except Exception as e:
        return jsonify({"error": f"AI Engine Error: {str(e)}"}), 500

from flask import send_file

@app.route('/download-report')
def download_report():
    try:
        # This sends the actual file generated by Member 1's code
        return send_file('final_report.txt', as_attachment=True)
    except Exception as e:
        return jsonify({"error": "Report file not found"}), 404
    
if __name__ == '__main__':
    print("🚀 Server Running! Open: http://localhost:5000")
    app.run(port=5000, debug=True)